#!/usr/bin/bash 
# Read number from file and print the factors in the file 

FILE=$1

while read NUMBERS;
do
	factors=($(factor $NUMBERS))
	echo "$NUMBERS=$(($NUMBERS/${factors[1]}))*${factors[1]}"
done < $FILE
