#!/usr/bin/bash 
#factors.sh

if [$# -ne 1]; 
then
	echo "Usage: $0 <filename>"
	exit 1
fi
	

FILE="$1"

while read -r NUMBERS;
do
	factors=($(factor $NUMBERS))
	echo "$NUMBERS=$(($NUMBERS/${factors[1]}))*${factors[1]}"
done < "$FILE"
