#!/usr/bin/python3
from sys import argv

def is_prime(number):
    if number < 2:
        return False
    for i in range(2, int(number**0.5) + 1):
        if number % i == 0:
            return False
    return True

def rsa_factorization(num):
    print("{:d}=".format(num), end='')

    if num == 2:
        print("2*1")
        return

    for i in range(2, num + 1):
        if num % i == 0 and is_prime(i):
            factor = num // i
            if is_prime(factor):
                print("{}*{}".format(factor, i))
                return

if len(argv) != 2:
    print("Usage: ./rsa <filename>")
    exit(1)

filename = argv[1]

with open(filename) as f:
    for line in f:
        num = int(line.strip())
        rsa_factorization(num)

