#!/usr/bin/python3
"""
RSA Factorization Script.

This script reads a file containing RSA number and performs prime factorization.
For each RSA number n, the script finds number p and q such that n = p * q.

Usage: ./rsa_factorization <filaname>
- <filename>: A file containing RSA numbers, one per line.

The prime factorization is printed in the format: n=p*q
"""

from sys import argv

def is_prime(number):
    """
    Check if a number is prime.

    Args:
    -number (int): The number to check.

    Returns:
    - bool: True if the number is prime, False otherwise.
    """

    if number < 2:
        return False
    for i in range(2, int(number**0.5) + 1):
        if number % i == 0:
            return False
    return True

def rsa_factorization(num):
    """
    Perform RSA factorization for a given number and print the result.

    Args:
    - num (int): The RSA number to factorize.
    """

    print("{:d}=".format(num), end='')

    if num == 2:
        print("2*1")
        return

    for i in range(2, int(num**0.5) + 1):
        if num % i == 0 and is_prime(i):
            factor = num // i
            if is_prime(factor):
                print("{}*{}".format(factor, i))
                return

if len(argv) != 2:
    print("Usage: ./rsa_factorization <filename>")
    exit(1)

filename = argv[1]

with open(filename) as f:
    for line in f:
        num = int(line.strip())
        rsa_factorization(num)
